"""Build L_Foliage_Lookdev - the controlled fixture for the foliage master.

WHY CARDS ARE GENERATED HERE
-----------------------------
The foliage master (M_Master_Toon_Foliage) is masked + two-sided + swaying,
and before this builder it had no geometry to sit on. Foliage cards are the
classical fixture: a vertical quad, alpha-cut by the cover SDF (T_SDF_Leaf),
fanned/crossed into clusters. The meshes are generated as OBJ from pure
stdlib - the same "values ported, pixels/geometry regenerated" contract the
textures use - and imported through Interchange.

The card is a PLAIN quad on purpose: the silhouette is the opacity mask's
job, not the mesh's. Three topologies cover the cases:
  card_quad   - one quad; terminator + mask read with zero occlusion noise
  card_cross  - two quads at 90 degrees; the classic bush/tuft read, and the
                first place two-sided shading contradicts itself
  card_fan    - three quads fanned at -55/0/+55 degrees; depth stacking and
                the sway response at clustered scale

Each card instance gets one of the foliage instances (Fern/Hedge) so the
fixture judges the INSTANCED look, not the bare master.
"""
from __future__ import annotations

import math
import os
from pathlib import Path

import unreal

# standalone launch: Python/ must be on sys.path or `import spine_lib` fails
# and the editor exits 0 having built nothing (measured 2026-10-03)
sys.path.insert(0, str(Path(__file__).resolve().parent))

import spine_lib as lib  # noqa: E402
import lookdev_lib  # noqa: E402

NAME = "L_Foliage_Lookdev"
MAP_DIR = "/Game/Maps"
MESH_DIR = "/Game/Meshes/Foliage"
PNG_STAGING = Path(__file__).resolve().parents[1] / "Saved" / "GeneratedMeshes"

CARD_SIZE = 130.0          # uu, square card
ENGINE_SHAPES = {
    "plane": "/Engine/BasicShapes/Plane.Plane",
    "cube": "/Engine/BasicShapes/Cube.Cube",
}
INSTANCES = {
    "fern": "/Game/Materials/Instances/MI_Foliage_Fern",
    "hedge": "/Game/Materials/Instances/MI_Foliage_Hedge",
}
SUN_ROT = (-38.0, 210.0, 0.0)      # (pitch, yaw, roll) - see build_gouache_lookdev
SUN_INTENSITY = 3.2
SKY_INTENSITY = 0.9
CAM_LOC = (340.0, -420.0, 160.0)
CAM_LOOK_AT = (0.0, 0.0, 70.0)


# ---------------------------------------------------------------------------
# OBJ generation - cards in XZ plane (vertical), normal +Y, units = uu
# ---------------------------------------------------------------------------

def _quad_verts(size: float, cx: float = 0.0, cz: float = 0.0):
    """A square quad's corners, centred at (cx, cz), 0.5*size half-extent."""
    h = size / 2.0
    return [(cx - h, 0.0, cz - h), (cx + h, 0.0, cz - h),
            (cx + h, 0.0, cz + h), (cx - h, 0.0, cz + h)]


def gen_card_obj(kind: str, out_path: Path) -> dict:
    """Write one card mesh as OBJ. Returns {verts, tris} for the report.

    Topologies:
      quad   - one card at origin
      cross  - two cards, second rotated 90 degrees about Y (vertical axis)
      fan    - three cards rotated -55/0/+55 degrees, base-anchored
    """
    verts, normals, uvs, faces = [], [], [], []

    def emit_quad(corners, nrm):
        base = len(verts)
        for (x, y, z) in corners:
            verts.append((x, y, z))
            normals.append(nrm)
        uvs.extend([(0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0)])
        faces.append((base + 1, base + 2, base + 3))
        faces.append((base + 1, base + 3, base + 4))

    def rot_y(pts, deg, cx=0.0, cz=CARD_SIZE / 2.0):
        a = math.radians(deg)
        c, s = math.cos(a), math.sin(a)
        out = []
        for (x, y, z) in pts:
            dx, dz = x - cx, z - cz
            out.append((cx + dx * c + dz * s, y, cz - dx * s + dz * c))
        return out

    if kind == "quad":
        emit_quad(_quad_verts(CARD_SIZE), (0.0, -1.0, 0.0))
    elif kind == "cross":
        q = _quad_verts(CARD_SIZE)
        emit_quad(q, (0.0, -1.0, 0.0))
        emit_quad(rot_y(q, 90.0), (1.0, 0.0, 0.0))
    elif kind == "fan":
        for deg in (-55.0, 0.0, 55.0):
            emit_quad(rot_y(_quad_verts(CARD_SIZE), deg),
                      (math.sin(math.radians(deg)), -math.cos(math.radians(deg)),
                       0.0))
    else:
        raise ValueError(f"unknown card topology {kind!r}")

    lines = ["# generated by build_foliage_lookdev.py - do not hand-edit"]
    for (x, y, z) in verts:
        lines.append(f"v {x:.3f} {y:.3f} {z:.3f}")
    for (x, y, z) in normals:
        lines.append(f"vn {x:.3f} {y:.3f} {z:.3f}")
    for (u, v) in uvs:
        lines.append(f"vt {u:.4f} {v:.4f}")
    for (a, b, c) in faces:
        lines.append(f"f {a}/{a} {b}/{b} {c}/{c}")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="ascii")
    return {"verts": len(verts), "tris": len(faces)}


CARDS = (
    ("SM_Foliage_CardQuad", "quad"),
    ("SM_Foliage_CardCross", "cross"),
    ("SM_Foliage_CardFan", "fan"),
)


def import_cards() -> dict:
    """Generate + import the three card meshes. Returns path/asset info."""
    lib.ensure_dir(MESH_DIR)
    tasks = []
    made = {}
    for name, kind in CARDS:
        obj = PNG_STAGING / f"{name}.obj"
        stats = gen_card_obj(kind, obj)
        task = unreal.AssetImportTask()
        task.filename = str(obj)
        task.destination_path = MESH_DIR
        task.destination_name = name
        task.automated = True
        task.save = True
        task.replace_existing = True
        tasks.append(task)
        made[name] = stats
    unreal.AssetToolsHelpers.get_asset_tools().import_asset_tasks(tasks)
    for name in made:
        asset = unreal.load_asset(f"{MESH_DIR}/{name}.{name}")
        made[name]["imported"] = asset is not None
        lib.log(f"CARD {name}: {made[name]} ")
    return made


# ---------------------------------------------------------------------------
# Level (mirrors build_gouache_lookdev's helpers)
# ---------------------------------------------------------------------------

def resolve_world_factory():
    for nm in ("WorldFactory", "WorldFactoryNew", "WorldFactoryNewLevel"):
        cls = getattr(unreal, nm, None)
        if cls is not None:
            return cls
    return None


def ensure_level() -> str:
    """Open the fixture level via lookdev_lib (phantom purge, create, save,
    then load) - see lookdev_lib.ensure_level for why this is shared."""
    status = lookdev_lib.ensure_level(NAME)
    lib.log(f"level {NAME}: {' '.join(status['actions'])}")
    return status["asset_path"]


def spawn_mesh(label, mesh_path, location, scale, material, yaw=0.0,
               pitch=0.0):
    mesh = unreal.load_asset(mesh_path)
    if mesh is None:
        lib.log(f"WARN {label}: mesh missing {mesh_path}")
        return None
    actor = unreal.EditorLevelLibrary.spawn_actor_from_class(
        unreal.StaticMeshActor, unreal.Vector(*location),
        unreal.Rotator(roll=0.0, pitch=float(pitch), yaw=float(yaw)))
    actor.set_actor_label(label)
    comp = actor.get_component_by_class(unreal.StaticMeshComponent)
    comp.set_mobility(unreal.ComponentMobility.MOVABLE)
    comp.set_static_mesh(mesh)
    if scale != 1.0:
        actor.set_actor_scale3d(unreal.Vector(scale, scale, scale))
    if material is not None:
        comp.set_material(0, material)
    comp.set_mobility(unreal.ComponentMobility.STATIC)
    return actor


def spawn_ground():
    return spawn_mesh("FLD_Ground", ENGINE_SHAPES["plane"], (0, 0, 0), 14.0,
                      None)


def spawn_lights():
    pitch, yaw, roll = SUN_ROT
    sun = unreal.EditorLevelLibrary.spawn_actor_from_class(
        unreal.DirectionalLight, unreal.Vector(0, 0, 4000),
        unreal.Rotator(roll=float(roll), pitch=float(pitch), yaw=float(yaw)))
    sun.set_actor_label("FLD_Sun")
    try:
        c = sun.get_component_by_class(unreal.DirectionalLightComponent)
        c.set_mobility(unreal.ComponentMobility.MOVABLE)
        c.set_intensity(SUN_INTENSITY)
        c.set_mobility(unreal.ComponentMobility.STATIC)
    except Exception as exc:
        lib.log(f"WARN sun config: {str(exc)[:100]}")
    sky = unreal.EditorLevelLibrary.spawn_actor_from_class(
        unreal.SkyLight, unreal.Vector(0, 0, 1000))
    sky.set_actor_label("FLD_Sky")
    try:
        c = sky.get_component_by_class(unreal.SkyLightComponent)
        c.set_mobility(unreal.ComponentMobility.MOVABLE)
        c.set_intensity(SKY_INTENSITY)
        c.set_mobility(unreal.ComponentMobility.STATIC)
    except Exception as exc:
        lib.log(f"WARN sky config: {str(exc)[:100]}")
    return sun, sky


def spawn_camera():
    cam = unreal.EditorLevelLibrary.spawn_actor_from_class(
        unreal.CineCameraActor, unreal.Vector(*CAM_LOC),
        unreal.Rotator(0, 0, 0))
    cam.set_actor_label("FLD_Cam")
    try:
        comp = cam.get_component_by_class(unreal.CineCameraComponent)
        lib.try_set(comp, "current_focal_length", 55.0)
    except Exception as exc:
        lib.log(f"WARN camera focal: {str(exc)[:100]}")
    try:
        rot = unreal.KismetMathLibrary.find_look_at_rotation(
            unreal.Vector(*CAM_LOC), unreal.Vector(*CAM_LOOK_AT))
        cam.set_actor_rotation(rot)
    except Exception as exc:
        lib.log(f"WARN camera aim: {str(exc)[:100]}")
    return cam


# label, card, instance, loc, yaw, pitch
CARDS_IN_SCENE = (
    ("FLD_Fern_Quad",  "SM_Foliage_CardQuad",  "fern",  (-160, 40, 65),  12.0, 0.0),
    ("FLD_Fern_Cross", "SM_Foliage_CardCross", "fern",  (-40, -60, 65),  -25.0, 0.0),
    ("FLD_Hedge_Cross","SM_Foliage_CardCross", "hedge", (90, 50, 65),    40.0, 0.0),
    ("FLD_Hedge_Fan",  "SM_Foliage_CardFan",   "hedge", (230, -30, 65),  -12.0, 0.0),
    ("FLD_Fan_Tilted", "SM_Foliage_CardFan",   "fern",  (60, 140, 65),   150.0, -14.0),
)


def build() -> dict:
    lib.log(f"=== {NAME} ===")
    report = {"level": NAME, "errors": [], "warnings": [],
              "cards": {}, "scene": [], "materials": {}}

    cards = import_cards()
    report["cards"] = {k: v for k, v in cards.items()}
    missing = [k for k, v in cards.items() if not v.get("imported")]
    if missing:
        report["errors"].append(f"card import failed: {missing}")

    mats = {}
    for key, path in INSTANCES.items():
        asset = unreal.load_asset(path)
        mats[key] = {"path": path, "loaded": asset is not None}
        if asset is None:
            report["warnings"].append(f"{key}: instance missing {path}")

    path = ensure_level()
    report["level_asset"] = path

    spawn_ground()
    for label, card, inst_key, loc, yaw, pitch in CARDS_IN_SCENE:
        mat = unreal.load_asset(INSTANCES[inst_key])
        ok = spawn_mesh(label, f"{MESH_DIR}/{card}.{card}", loc, 1.0, mat,
                        yaw=yaw, pitch=pitch) is not None
        report["scene"].append({"label": label, "card": card,
                                "instance": inst_key, "spawned": ok})
        if not ok:
            report["errors"].append(f"{label}: spawn failed")

    spawn_lights()
    spawn_camera()

    saved = lookdev_lib.save_current_level(report["level_asset"])
    report["level_saved"] = saved

    actors = unreal.EditorLevelLibrary.get_all_level_actors() or []
    labels = [a.get_actor_label() for a in actors]
    report["census"] = {
        "total": len(actors),
        "static_mesh": len([a for a in actors
                            if isinstance(a, unreal.StaticMeshActor)]),
        "all_cards_present": all(r["label"] in labels
                                 for r in report["scene"]),
    }

    report["notes"] = {
        "sway": ("SwayAmount/SwaySpeed/SwayPhase are instance-level on "
                 "MI_Foliage_*/the master; sway is a WPO term, so stills "
                 "prove the mask and shading only - motion needs PIE."),
        "silhouette_is_mask": (
            "The cards are plain quads; the silhouette is T_SDF_Leaf cut by "
            "MaskCutoff/MaskSharpness. A ragged edge here is a mask/opacity "
            "problem, never a mesh problem."),
        "two_sided": ("The master is two-sided; the cross/fan topologies "
                      "exist precisely to expose back-face shading."),
    }
    report["ok"] = (not report["errors"]) and saved
    _write_report(report)
    lib.log(f"{NAME}: ok={report['ok']} cards={len(report['scene'])} "
            f"saved={saved}")
    return report


def _write_report(report: dict) -> None:
    """Persist the fixture's evidence next to the other Audit reports.

    The driver (Tools/build_lookdev_levels.py) gates on the .umap file, but a
    level existing is not the same as the level containing the right actors -
    this report is the census that closes that gap.
    """
    import json
    out = (Path(__file__).resolve().parents[1] / "Saved" / "Audit"
           / "foliage_lookdev_report.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=2), encoding="utf-8")


def main() -> int:
    return 0 if build()["ok"] else 1


if __name__ == "__main__":
    import sys
    sys.exit(main())
