"""Shared helpers for building the 304 film toon spine from code.

Every material and material function in this project is GENERATED by a script,
never copied as a .uasset. That is deliberate:

  * a binary blob cannot be reviewed in a pull request
  * a .uasset moved between projects keeps its old package path and breaks
  * UE 5.8 silently drops a material graph on a second cross-project rename
    (observed 2026-09-29: 751,265 -> 666,458 bytes, all 10 MaterialFunctionCall
    references gone, verify reported clean:true because it counted zero calls)

Generated content means a group member can regenerate the spine on any UE 5.8
checkout instead of receiving a file nobody can edit.

Run headless:
    UnrealEditor-Cmd.exe <project>.uproject ^
      -ExecutePythonScript="Python/build_spine.py" -stdout -unattended

Assert on the report FILE, not the log - unreal.log() is unreliable under
-stdout capture.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import unreal

# ---------------------------------------------------------------------------
# Layout
# ---------------------------------------------------------------------------

MATERIALS_ROOT = "/Game/Materials"
MASTER_DIR = f"{MATERIALS_ROOT}/Masters"
FUNCTION_DIR = f"{MATERIALS_ROOT}/Functions"
PROFILE_DIR = f"{MATERIALS_ROOT}/ToonProfiles"

REPORT = Path(os.environ.get("TEMP", ".")) / "spine_build_report.json"


def log(m):
    unreal.log("[SpineBuild] " + str(m))


# ---------------------------------------------------------------------------
# Asset creation
# ---------------------------------------------------------------------------

def ensure_dir(path):
    if not unreal.EditorAssetLibrary.does_directory_exist(path):
        unreal.EditorAssetLibrary.make_directory(path)


def asset_path(folder, name):
    return f"{folder}/{name}.{name}"


def get_or_create_material(name, folder=MASTER_DIR, rebuild=False):
    """Material, created if absent. rebuild=True deletes and recreates."""
    path = asset_path(folder, name)
    if unreal.EditorAssetLibrary.does_asset_exist(path):
        if not rebuild:
            return unreal.load_asset(path)
        log(f"rebuild: deleting {name}")
        unreal.EditorAssetLibrary.delete_asset(path)
    ensure_dir(folder)
    tools = unreal.AssetToolsHelpers.get_asset_tools()
    mat = tools.create_asset(name, folder, unreal.Material,
                             unreal.MaterialFactoryNew())
    if mat is None:
        raise RuntimeError(f"could not create material {name}")
    return mat


def get_or_create_function(name, rebuild=False):
    """MaterialFunction, created if absent."""
    path = asset_path(FUNCTION_DIR, name)
    if unreal.EditorAssetLibrary.does_asset_exist(path):
        if not rebuild:
            return unreal.load_asset(path)
        log(f"rebuild: deleting function {name}")
        unreal.EditorAssetLibrary.delete_asset(path)
    ensure_dir(FUNCTION_DIR)
    tools = unreal.AssetToolsHelpers.get_asset_tools()
    fn = tools.create_asset(name, FUNCTION_DIR, unreal.MaterialFunction,
                            unreal.MaterialFunctionFactoryNew())
    if fn is None:
        raise RuntimeError(f"could not create material function {name}")
    return fn


def try_set(obj, prop, value):
    """Best-effort set_editor_property. UE hides many fields behind has_editor_property."""
    try:
        if obj.has_editor_property(prop):
            obj.set_editor_property(prop, value)
            return True
    except Exception:
        pass
    return False


def save(asset):
    try:
        unreal.EditorAssetLibrary.save_loaded_asset(asset, only_if_is_dirty=False)
    except Exception as exc:
        log(f"save warning: {exc}")


# ---------------------------------------------------------------------------
# Expression creation
# ---------------------------------------------------------------------------

def expr(owner, cls, x=0, y=0):
    """Create an expression inside a Material or a MaterialFunction."""
    if isinstance(owner, unreal.MaterialFunction):
        return unreal.MaterialEditingLibrary.create_material_expression_in_function(
            owner, cls, x, y)
    return unreal.MaterialEditingLibrary.create_material_expression(owner, cls, x, y)


def scalar(owner, name, group, default, x=0, y=0, desc=None):
    e = expr(owner, unreal.MaterialExpressionScalarParameter, x, y)
    e.set_editor_property("parameter_name", name)
    e.set_editor_property("group", group)
    e.set_editor_property("default_value", float(default))
    _desc(e, desc)
    return e


def vector(owner, name, group, default, x=0, y=0, desc=None):
    e = expr(owner, unreal.MaterialExpressionVectorParameter, x, y)
    e.set_editor_property("parameter_name", name)
    e.set_editor_property("group", group)
    e.set_editor_property("default_value", unreal.LinearColor(*default))
    _desc(e, desc)
    return e


def constant(owner, rgb, x=0, y=0):
    e = expr(owner, unreal.MaterialExpressionConstant3Vector, x, y)
    e.set_editor_property("constant", unreal.LinearColor(*rgb))
    return e


def scalar_const(owner, v, x=0, y=0):
    e = expr(owner, unreal.MaterialExpressionConstant, x, y)
    e.set_editor_property("r", float(v))
    return e


def texture_param(owner, name, group, x=0, y=0, desc=None):
    """Texture parameter. Never auto-assigns a texture: an unwired parameter
    samples the default grey, which is a safe placeholder and keeps the material
    free of banned /Engine/ content (see material_lib.BANNED_TEXTURE_PATHS)."""
    e = expr(owner, unreal.MaterialExpressionTextureSampleParameter2D, x, y)
    e.set_editor_property("parameter_name", name)
    e.set_editor_property("group", group)
    _desc(e, desc)
    return e


def _desc(e, text):
    if not text:
        return
    for prop in ("desc", "parameter_desc", "Desc"):
        try:
            if e.has_editor_property(prop):
                e.set_editor_property(prop, text)
                return
        except Exception:
            continue


# ---------------------------------------------------------------------------
# Function I/O
# ---------------------------------------------------------------------------

def add_function_input(fn, name, input_type, preview=(0.0, 0.0, 0.0, 0.0), x=-800, y=0):
    """Add a FunctionInput to a MaterialFunction and return it.

    input_type is an unreal.FunctionInputType scalar, e.g.
        unreal.FunctionInputType.FUNCTION_INPUT_SCALAR
    """
    e = expr(fn, unreal.MaterialExpressionFunctionInput, x, y)
    e.set_editor_property("input_name", name)
    try:
        e.set_editor_property("input_type", input_type)
    except Exception as exc:
        log(f"add_function_input {name}: input_type set failed ({exc})")
    try:
        e.set_editor_property("preview_value", unreal.Vector4(*preview))
    except Exception:
        pass
    return e


def add_function_output(fn, name, x=800, y=0):
    """Add a FunctionOutput.

    UE 5.8 has NO FunctionOutputType enum and no output_type/material_property
    field on MaterialExpressionFunctionOutput - verified by probing a real
    function (MF_ColorRamp3) on 2026-09-30. The output type is inferred from
    what is wired into it. Only output_name and desc are settable.
    """
    e = expr(fn, unreal.MaterialExpressionFunctionOutput, x, y)
    e.set_editor_property("output_name", name)
    return e


# ---------------------------------------------------------------------------
# Wiring
# ---------------------------------------------------------------------------

def connect(src, src_output, dst, dst_input):
    """Connect, trying a list of candidate pin names.

    UE 5.8 exposes 'True'/'False' on StaticSwitchParameter (not A/B), and
    generic pins are often just 'input' or ''. Returns True on first success.
    """
    lib = unreal.MaterialEditingLibrary
    if src_output is None:
        src_output = ""
    if isinstance(dst_input, (list, tuple)):
        for pin in dst_input:
            try:
                if lib.connect_material_expressions(src, src_output, dst, pin) is not False:
                    return True
            except Exception:
                continue
        return False
    try:
        return lib.connect_material_expressions(src, src_output, dst,
                                               dst_input) is not False
    except Exception:
        return False


def unary(src, dst):
    """Wire a single-input node (Abs, Saturate, OneMinus, Frac, Sine, ...)."""
    lib = unreal.MaterialEditingLibrary
    try:
        pins = [str(p) for p in lib.get_material_expression_input_names(dst)]
    except Exception:
        pins = []
    candidates = pins + ["Input", "input", ""]
    for pin in candidates:
        if connect(src, "", dst, pin):
            return True
    # last resort: the node's own input property
    for prop in ("input", "Input"):
        try:
            dst.get_editor_property(prop).connect(0, src)
            return True
        except Exception:
            continue
    return False


def binary(a, b, dst):
    """Wire A/B on a two-input math node."""
    ok_a = connect(a, "", dst, ["A", "a", "Input0"])
    ok_b = connect(b, "", dst, ["B", "b", "Input1"])
    return ok_a and ok_b


def ternary(a, b, c, dst):
    ok_a = connect(a, "", dst, ["A", "a"])
    ok_b = connect(b, "", dst, ["B", "b"])
    ok_c = connect(c, "", dst, ["Alpha", "C", "c"])
    return ok_a and ok_b and ok_c


def connect_property(src, material_property, src_output=""):
    unreal.MaterialEditingLibrary.connect_material_property(
        src, src_output, material_property)


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------

def function_calls(material):
    """Every MaterialFunctionCall path in a material graph."""
    lib = unreal.MaterialEditingLibrary
    out = []
    for e in lib.get_material_expressions(material) or []:
        if e is not None and type(e).__name__ == "MaterialExpressionMaterialFunctionCall":
            try:
                mf = e.get_editor_property("material_function")
                if mf:
                    out.append(mf.get_path_name())
            except Exception:
                pass
    return out


def expression_count(material):
    lib = unreal.MaterialEditingLibrary
    try:
        return len(list(lib.get_material_expressions(material) or []))
    except Exception:
        return 0


def function_expression_count(fn):
    """Expressions inside a MaterialFunction (get_material_expressions is
    Material-only in UE 5.8)."""
    lib = unreal.MaterialEditingLibrary
    try:
        return len(list(lib.get_material_function_expressions(fn) or []))
    except Exception:
        return 0


def verify_function(name, min_expressions=15, expect_underscore_output=True):
    """Assert a generated MaterialFunction actually contains a graph."""
    path = asset_path(FUNCTION_DIR, name)
    fn = unreal.load_asset(path)
    result = {"path": path, "loads": fn is not None, "ok": False}

    if fn is None:
        log(f"VERIFY FAIL {name}: does not load")
        return result

    n = function_expression_count(fn)
    result["expression_count"] = n

    if n == 0:
        result["error"] = "ZERO expressions - function is empty, not verified"
    elif n < min_expressions:
        result["error"] = f"only {n} expressions (expected >= {min_expressions})"

    result["ok"] = not result.get("error")
    log(f"VERIFY {name}: ok={result['ok']} exprs={n} {result.get('error', '')}")
    return result


def verify_material(name, expected_calls, min_expressions=10):
    """Assert a generated material is real.

    Guards against the zero-node false pass: a material that reports 0 function
    calls is NOT verified, it is empty.
    """
    path = asset_path(MASTER_DIR, name)
    mat = unreal.load_asset(path)
    result = {"path": path, "loads": mat is not None, "ok": False}

    if mat is None:
        log(f"VERIFY FAIL {name}: does not load")
        return result

    calls = sorted({c.rsplit("/", 1)[-1].split(".", 1)[0] for c in function_calls(mat)})
    nexpr = expression_count(mat)

    result["mf_calls"] = calls
    result["expression_count"] = nexpr

    missing = [c for c in expected_calls if c not in calls]
    result["missing_calls"] = missing

    # a zero-count graph is empty, not clean
    if len(expected_calls) > 0 and len(calls) == 0:
        result["error"] = "ZERO function calls - graph is empty, not verified"
    elif missing:
        result["error"] = f"missing calls: {missing}"
    elif nexpr < min_expressions:
        result["error"] = f"only {nexpr} expressions (expected >= {min_expressions})"

    result["ok"] = not result.get("error")
    log(f"VERIFY {name}: ok={result['ok']} calls={len(calls)} exprs={nexpr} "
        f"{result.get('error', '')}")
    return result


def save_all():
    try:
        unreal.EditorLoadingAndSavingUtils.save_dirty_packages(True, True)
        log("saved dirty packages")
    except Exception as exc:
        log(f"save_all warning: {exc}")


def write_report(report):
    REPORT.write_text(json.dumps(report, indent=2), encoding="utf-8")
    log(f"report -> {REPORT}")

def function_inputs_for(fn, node):
    """Wired upstream nodes of `node` inside a MaterialFunction.

    UE 5.8 has no get_material_expression_input(expr, pin). For FUNCTIONS the
    working call is get_inputs_for_material_function_expression(fn, node) - the
    Material-only variant takes `material` and raises a conversion error here.
    Verified by probe 2026-09-30.
    """
    lib = unreal.MaterialEditingLibrary
    try:
        return [x for x in lib.get_inputs_for_material_function_expression(fn, node)
                if x is not None]
    except Exception:
        return []


def material_inputs_for(mat, node):
    try:
        return [x for x in unreal.MaterialEditingLibrary
                .get_inputs_for_material_expression(mat, node) if x is not None]
    except Exception:
        return []


def graph_reachability(owner, nodes, is_function):
    """Backward BFS from every FunctionOutput / material property output.

    Answering "does every node contribute to a rendered output?" is the only
    meaningful dead-code test. A forward BFS from inputs is wrong: parameters
    and constants are legitimate graph SOURCES and would be miscounted as
    orphans (they have no upstream).

    Returns (live, dead, outputs_wired, unused_inputs).
    """
    nodes = list(nodes)
    get_ins = function_inputs_for if is_function else material_inputs_for

    # reverse edges: upstream -> downstream
    consumers = {}
    for n in nodes:
        for u in get_ins(owner, n):
            consumers.setdefault(id(u), []).append(id(n))

    outputs = [n for n in nodes
               if type(n).__name__ == "MaterialExpressionFunctionOutput"]
    outputs_wired = {type(n).__name__: bool(get_ins(owner, n)) for n in outputs}

    by_id = {id(n): n for n in nodes}

    # seed the walk at the sinks (nothing consumes them) and walk upstream
    live = set()
    stack = [id(n) for n in nodes if id(n) not in consumers]
    live.update(stack)
    while stack:
        cur = stack.pop()
        node = by_id.get(cur)
        if node is None:
            continue
        for u in get_ins(owner, node):
            if id(u) not in live:
                live.add(id(u)); stack.append(id(u))

    dead = len(nodes) - len(live)

    # inputs that reach nothing
    unused_inputs = []
    for n in nodes:
        if type(n).__name__ == "MaterialExpressionFunctionInput":
            if id(n) not in live:
                unused_inputs.append(str(n.get_editor_property("input_name")))

    return len(live), dead, outputs_wired, unused_inputs


def verify_function_graph(name, max_dead=0, require_outputs=True):
    """Full structural check for a generated MaterialFunction.

    Guards the failure that counting expressions cannot: a function whose nodes
    exist but whose chain never reaches the outputs renders nothing.
    """
    path = asset_path(FUNCTION_DIR, name)
    fn = unreal.load_asset(path)
    result = {"path": path, "loads": fn is not None, "ok": False}
    if fn is None:
        log(f"VERIFY FAIL {name}: does not load")
        return result

    exprs = list(unreal.MaterialEditingLibrary.get_material_function_expressions(fn) or [])
    result["expression_count"] = len(exprs)

    live, dead, outs, unused = graph_reachability(fn, exprs, is_function=True)
    result["live_nodes"] = live
    result["dead_nodes"] = dead
    result["outputs_wired"] = outs
    result["unused_inputs"] = unused

    if len(exprs) == 0:
        result["error"] = "ZERO expressions"
    elif dead > max_dead:
        result["error"] = f"{dead} nodes contribute to no output"
    elif require_outputs and outs and not all(outs.values()):
        deadouts = [k for k, v in outs.items() if not v]
        result["error"] = f"outputs have no source: {deadouts}"
    result["ok"] = not result.get("error")
    log(f"VERIFY {name}: ok={result['ok']} exprs={len(exprs)} live={live} "
        f"dead={dead} unused_inputs={unused} {result.get('error','')}")
    return result
