"""Shared helpers for building the 304 film toon spine from code.

Every material and material function in this project is GENERATED by a script,
never copied as a .uasset. That is deliberate:

  * a binary blob cannot be reviewed in a pull request
  * a .uasset moved between projects keeps its old package path and breaks
  * UE 5.8 silently drops a material graph on a second cross-project rename
    (observed 2026-09-29: 751,265 -> 666,458 bytes, all 10 MaterialFunctionCall
    references gone, verify reported clean:true because it counted zero calls)

Generated content means a group member can regenerate the spine on any UE 5.8
checkout instead of receiving a file nobody can edit.

Run headless:
    UnrealEditor-Cmd.exe <project>.uproject ^
      -ExecutePythonScript="Python/build_spine.py" -stdout -unattended

Assert on the report FILE, not the log - unreal.log() is unreliable under
-stdout capture.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

import unreal

# ---------------------------------------------------------------------------
# Layout
# ---------------------------------------------------------------------------

MATERIALS_ROOT = "/Game/Materials"
MASTER_DIR = f"{MATERIALS_ROOT}/Masters"
FUNCTION_DIR = f"{MATERIALS_ROOT}/Functions"
PROFILE_DIR = f"{MATERIALS_ROOT}/ToonProfiles"

REPORT = Path(os.environ.get("TEMP", ".")) / "spine_build_report.json"


def log(m):
    unreal.log("[SpineBuild] " + str(m))


# ---------------------------------------------------------------------------
# Asset creation
# ---------------------------------------------------------------------------

def ensure_dir(path):
    if not unreal.EditorAssetLibrary.does_directory_exist(path):
        unreal.EditorAssetLibrary.make_directory(path)


def asset_path(folder, name):
    return f"{folder}/{name}.{name}"


def _wipe_expressions(owner, is_function):
    """Remove every expression from an existing asset, in place.

    The per-node deleter (delete_material_expression) takes a MATERIAL as its
    first argument and raises for functions, so the loop variant wiped nothing
    and a rebuild-in-place produced a doubled graph (30+30 nodes feeding two
    sets of outputs). UE 5.8 ships bulk deleters for both containers - use
    those and read the count back.
    """
    me = unreal.MaterialEditingLibrary
    try:
        # one bulk pass can leave a still-referenced generation behind
        # (measured: 59 -> 29 with return None), so loop until the count stops
        # moving or the graph is empty
        prev = -1
        for _ in range(24):
            if is_function:
                me.delete_all_material_expressions_in_function(owner)
                remain = len(me.get_material_function_expressions(owner) or [])
            else:
                me.delete_all_material_expressions(owner)
                remain = len(me.get_material_expressions(owner) or [])
            if remain == 0 or remain == prev:
                break
            prev = remain
        return remain
    except Exception as exc:
        log(f"wipe failed on {owner.get_name()}: {str(exc)[:100]}")
        return -1


def get_or_create_material(name, folder=MASTER_DIR, rebuild=False):
    """Material, created if absent. rebuild=True wipes the graph in place.

    FIX 2026-10-03: the old path deleted the asset and created a fresh one.
    Delete is refused while any loaded consumer holds a reference - and when it
    is NOT refused, the new object leaves every in-memory consumer pointing at
    the DEAD object: the master's function-call nodes broke the moment
    MF_ColorRamp3 was recreated, and every instance failed with "(Node
    StaticSwitchParameter) Missing A input". Worse, a refused delete left the
    package flagged corrupt (ForceDeleteObject warning). Rebuilding IN PLACE -
    wipe the graph to zero, then re-add - keeps object identity, so references
    stay valid by construction and the graph still starts empty.
    """
    path = asset_path(folder, name)
    if unreal.EditorAssetLibrary.does_asset_exist(path):
        if not rebuild:
            return unreal.load_asset(path)
        log(f"rebuild: in-place wipe of {name}")
        mat = unreal.load_asset(path)
        remaining = _wipe_expressions(mat, is_function=False)
        if remaining:
            raise RuntimeError(
                f"{name}: wipe left {remaining} expressions - refusing to "
                f"build a doubled graph")
        log(f"rebuild: {name} graph cleared")
        return mat
    ensure_dir(folder)
    tools = unreal.AssetToolsHelpers.get_asset_tools()
    mat = tools.create_asset(name, folder, unreal.Material,
                             unreal.MaterialFactoryNew())
    if mat is None:
        raise RuntimeError(f"could not create material {name}")
    return mat


def get_or_create_function(name, rebuild=False):
    """MaterialFunction, created if absent (in-place rebuild semantics)."""
    path = asset_path(FUNCTION_DIR, name)
    if unreal.EditorAssetLibrary.does_asset_exist(path):
        if not rebuild:
            return unreal.load_asset(path)
        log(f"rebuild: in-place wipe of function {name}")
        fn = unreal.load_asset(path)
        remaining = _wipe_expressions(fn, is_function=True)
        if remaining:
            raise RuntimeError(
                f"{name}: wipe left {remaining} expressions - refusing to "
                f"build a doubled graph")
        log(f"rebuild: {name} graph cleared")
        return fn
    ensure_dir(FUNCTION_DIR)
    tools = unreal.AssetToolsHelpers.get_asset_tools()
    fn = tools.create_asset(name, FUNCTION_DIR, unreal.MaterialFunction,
                            unreal.MaterialFunctionFactoryNew())
    if fn is None:
        raise RuntimeError(f"could not create material function {name}")
    return fn


def try_set(obj, prop, value):
    """Set an editor property, tolerating UE fields that do not exist.

    FIX 2026-10-02: this used to gate on `obj.has_editor_property(prop)` first.
    That method DOES NOT EXIST on material expressions in this engine build
    (measured: toon_surface_probe.json), so every call raised AttributeError
    and was swallowed - `try_set(toon_node, "toon_profile", profile)` returned
    False and bound nothing, silently, while the caller carried on. The build
    only failed once verify_material learned to check the binding.

    Attempting the set directly is both simpler and correct: UE raises a
    descriptive error for an unknown property, which the except already
    handles. Existence is then VERIFIED by reading the value back, which is the
    only check that actually proves anything.
    """
    try:
        obj.set_editor_property(prop, value)
        return True
    except Exception as exc:
        log(f"try_set {prop} failed: {str(exc)[:120]}")
        return False


def save(asset):
    try:
        unreal.EditorAssetLibrary.save_loaded_asset(asset, only_if_is_dirty=False)
    except Exception as exc:
        log(f"save warning: {exc}")


# ---------------------------------------------------------------------------
# Expression creation
# ---------------------------------------------------------------------------

def expr(owner, cls, x=0, y=0):
    """Create an expression inside a Material or a MaterialFunction."""
    if isinstance(owner, unreal.MaterialFunction):
        return unreal.MaterialEditingLibrary.create_material_expression_in_function(
            owner, cls, x, y)
    return unreal.MaterialEditingLibrary.create_material_expression(owner, cls, x, y)


def scalar(owner, name, group, default, x=0, y=0, desc=None):
    e = expr(owner, unreal.MaterialExpressionScalarParameter, x, y)
    e.set_editor_property("parameter_name", name)
    e.set_editor_property("group", group)
    e.set_editor_property("default_value", float(default))
    _desc(e, desc)
    return e


def vector(owner, name, group, default, x=0, y=0, desc=None):
    e = expr(owner, unreal.MaterialExpressionVectorParameter, x, y)
    e.set_editor_property("parameter_name", name)
    e.set_editor_property("group", group)
    e.set_editor_property("default_value", unreal.LinearColor(*default))
    _desc(e, desc)
    return e


def constant(owner, rgb, x=0, y=0):
    e = expr(owner, unreal.MaterialExpressionConstant3Vector, x, y)
    e.set_editor_property("constant", unreal.LinearColor(*rgb))
    return e


def scalar_const(owner, v, x=0, y=0):
    e = expr(owner, unreal.MaterialExpressionConstant, x, y)
    e.set_editor_property("r", float(v))
    return e


def texture_param(owner, name, group, x=0, y=0, desc=None):
    """Texture parameter. Never auto-assigns a texture: an unwired parameter
    samples the default grey, which is a safe placeholder and keeps the material
    free of banned /Engine/ content (see material_lib.BANNED_TEXTURE_PATHS)."""
    e = expr(owner, unreal.MaterialExpressionTextureSampleParameter2D, x, y)
    e.set_editor_property("parameter_name", name)
    e.set_editor_property("group", group)
    _desc(e, desc)
    return e


def _desc(e, text):
    if not text:
        return
    for prop in ("desc", "parameter_desc", "Desc"):
        try:
            if e.has_editor_property(prop):
                e.set_editor_property(prop, text)
                return
        except Exception:
            continue


# ---------------------------------------------------------------------------
# Function I/O
# ---------------------------------------------------------------------------

def add_function_input(fn, name, input_type, preview=(0.0, 0.0, 0.0, 0.0), x=-800, y=0):
    """Add a FunctionInput to a MaterialFunction and return it.

    input_type is an unreal.FunctionInputType scalar, e.g.
        unreal.FunctionInputType.FUNCTION_INPUT_SCALAR
    """
    e = expr(fn, unreal.MaterialExpressionFunctionInput, x, y)
    e.set_editor_property("input_name", name)
    try:
        e.set_editor_property("input_type", input_type)
    except Exception as exc:
        log(f"add_function_input {name}: input_type set failed ({exc})")
    try:
        e.set_editor_property("preview_value", unreal.Vector4(*preview))
    except Exception:
        pass
    return e


def add_function_output(fn, name, x=800, y=0):
    """Add a FunctionOutput.

    UE 5.8 has NO FunctionOutputType enum and no output_type/material_property
    field on MaterialExpressionFunctionOutput - verified by probing a real
    function (MF_ColorRamp3) on 2026-09-30. The output type is inferred from
    what is wired into it. Only output_name and desc are settable.
    """
    e = expr(fn, unreal.MaterialExpressionFunctionOutput, x, y)
    e.set_editor_property("output_name", name)
    return e


# ---------------------------------------------------------------------------
# Wiring
# ---------------------------------------------------------------------------

def _pin_names(dst):
    """Ordered input pin names of `dst` as THIS build's binder expects them."""
    try:
        return [str(p) for p in
                unreal.MaterialEditingLibrary
                .get_material_expression_input_names(dst)]
    except Exception:
        return []


def _resolve_pin(dst, wanted):
    """Match a wanted pin name against the node's real pins.

    The binder matches by exact display name, and this build's names are not
    guessable: Power exposes Base/Exp (not A/B), Length has ONE unnamed pin,
    If spells its result pins 'A > B' with spaces. Guessing produced silent
    no-ops and a master that fell back to the default material. Probe first,
    guess last.
    """
    pins = _pin_names(dst)
    if not pins:
        return wanted
    norm = lambda s: s.replace(" ", "").lower()
    for p in pins:
        if norm(p) == norm(wanted):
            return p
    return wanted


def connect(src, src_output, dst, dst_input):
    """Connect, trying a list of candidate pin names.

    UE 5.8 exposes 'True'/'False' on StaticSwitchParameter (not A/B), 'Base'/
    'Exp' on Power (not A/B), and an unnamed single pin on Length. Returns True
    on first success.
    """
    lib = unreal.MaterialEditingLibrary
    if src_output is None:
        src_output = ""
    if isinstance(dst_input, (list, tuple)):
        for pin in dst_input:
            try:
                if lib.connect_material_expressions(src, src_output, dst,
                                                    _resolve_pin(dst, pin)) \
                        is not False:
                    return True
            except Exception:
                continue
        return False
    try:
        return lib.connect_material_expressions(src, src_output, dst,
                                               _resolve_pin(dst, dst_input)) \
            is not False
    except Exception:
        return False


def length2(fn, a, b, x=0, y=0):
    """Length of a 2D pair built from two scalars.

    Length exposes ONE unnamed input on this build ('' connects, 'A'/'B' do
    not), so scalar pairs must go through AppendVector - the same lesson the
    Voronoi feature-point path already learned.
    """
    pair = expr(fn, unreal.MaterialExpressionAppendVector, x, y)
    connect(a, "", pair, ["A", "a"])
    connect(b, "", pair, ["B", "b"])
    ln = expr(fn, unreal.MaterialExpressionLength, x + 160, y)
    connect(pair, "", ln, ["", "None"])
    return ln


def unary(src, dst):
    """Wire a single-input node (Abs, Saturate, OneMinus, Frac, Sine, ...).

    FIX 2026-10-03 - a silent-success bug that shipped a broken material.
    MaterialEditingLibrary.get_material_expression_input_names() returns the
    Python string "None" (not an empty string) for the unnamed input of
    Saturate and OneMinus on UE 5.8:

        MaterialExpressionSaturate  input_names == ["None"]
        MaterialExpressionOneMinus  input_names == ["None"]

    Connect() then resolves the literal name "None", which UE accepts and
    silently treats as an UNSET pin, so connect() returned True while nothing
    was wired. The material compiled to "(Node Saturate) Missing Saturate
    input" and rendered as Default Material, with verify_material and the
    dead-node census both reporting clean.

    Measured pin names (Saved/Audit/pin_name_probe.json):
        Saturate / OneMinus  -> "None"   (the literal, must be normalised)
        Normalize            -> "VectorInput"
        SmoothStep           -> Min, Max, Value
        LinearInterpolate    -> A, B, Alpha
        Multiply / Add / Sub -> A, B

    A "None" pin name is normalised to the empty pin, which is what an unnamed
    input actually is. Return value is still not trusted by callers that need
    certainty - see connect() - but it now reflects reality.
    """
    lib = unreal.MaterialEditingLibrary
    try:
        pins = [str(p) for p in lib.get_material_expression_input_names(dst)]
    except Exception:
        pins = []
    # "None" is a genuine UE artefact for unnamed pins, not a missing value.
    # Leave "" alone - that IS the unnamed pin and connect() handles it.
    pins = ["" if p == "None" else p for p in pins]
    candidates = pins + ["Input", "input", "VectorInput", ""]
    for pin in candidates:
        if connect(src, "", dst, pin):
            return True
    # last resort: the node's own input property
    for prop in ("input", "Input"):
        try:
            dst.get_editor_property(prop).connect(0, src)
            return True
        except Exception:
            continue
    log(f"WARN unary failed to wire {type(dst).__name__}: no pin accepted "
        f"the connection (tried {candidates})")
    return False


def binary(a, b, dst):
    """Wire A/B on a two-input math node, using the node's REAL pin names.

    Most math nodes are A/B, but Power is Base/Exp on this build - probing the
    names first is what makes one helper correct for both.
    """
    pins = _pin_names(dst) or ["A", "B"]
    ok_a = connect(a, "", dst, [pins[0], "A", "a", "Input0"])
    ok_b = connect(b, "", dst, [pins[1] if len(pins) > 1 else "B",
                                "B", "b", "Input1"])
    return ok_a and ok_b


def ternary(a, b, c, dst):
    """Wire three inputs (Lerp: A/B/Alpha) using the node's REAL pin names."""
    pins = _pin_names(dst) or ["A", "B", "Alpha"]
    ok_a = connect(a, "", dst, [pins[0], "A", "a"])
    ok_b = connect(b, "", dst, [pins[1] if len(pins) > 1 else "B", "B", "b"])
    ok_c = connect(c, "", dst, [pins[2] if len(pins) > 2 else "Alpha",
                                "Alpha", "C", "c"])
    return ok_a and ok_b and ok_c


def connect_property(src, material_property, src_output=""):
    unreal.MaterialEditingLibrary.connect_material_property(
        src, src_output, material_property)


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------

def function_calls(material):
    """Every MaterialFunctionCall path in a material graph."""
    lib = unreal.MaterialEditingLibrary
    out = []
    for e in lib.get_material_expressions(material) or []:
        if e is not None and type(e).__name__ == "MaterialExpressionMaterialFunctionCall":
            try:
                mf = e.get_editor_property("material_function")
                if mf:
                    out.append(mf.get_path_name())
            except Exception:
                pass
    return out


def expression_count(material):
    lib = unreal.MaterialEditingLibrary
    try:
        return len(list(lib.get_material_expressions(material) or []))
    except Exception:
        return 0


def function_expression_count(fn):
    """Expressions inside a MaterialFunction (get_material_expressions is
    Material-only in UE 5.8)."""
    lib = unreal.MaterialEditingLibrary
    try:
        return len(list(lib.get_material_function_expressions(fn) or []))
    except Exception:
        return 0


def verify_function(name, min_expressions=15, expect_underscore_output=True):
    """Assert a generated MaterialFunction actually contains a graph."""
    path = asset_path(FUNCTION_DIR, name)
    fn = unreal.load_asset(path)
    result = {"path": path, "loads": fn is not None, "ok": False}

    if fn is None:
        log(f"VERIFY FAIL {name}: does not load")
        return result

    n = function_expression_count(fn)
    result["expression_count"] = n

    if n == 0:
        result["error"] = "ZERO expressions - function is empty, not verified"
    elif n < min_expressions:
        result["error"] = f"only {n} expressions (expected >= {min_expressions})"

    result["ok"] = not result.get("error")
    log(f"VERIFY {name}: ok={result['ok']} exprs={n} {result.get('error', '')}")
    return result


def verify_material(name, expected_calls, min_expressions=10):
    """Assert a generated material is real.

    Guards against the zero-node false pass: a material that reports 0 function
    calls is NOT verified, it is empty.
    """
    path = asset_path(MASTER_DIR, name)
    mat = unreal.load_asset(path)
    result = {"path": path, "loads": mat is not None, "ok": False}

    if mat is None:
        log(f"VERIFY FAIL {name}: does not load")
        return result

    calls = sorted({c.rsplit("/", 1)[-1].split(".", 1)[0] for c in function_calls(mat)})
    nexpr = expression_count(mat)

    result["mf_calls"] = calls
    result["expression_count"] = nexpr

    missing = [c for c in expected_calls if c not in calls]
    result["missing_calls"] = missing

    # Toon Profile binding, added 2026-10-02. A material can pass every check
    # above and still be shading on ENGINE DEFAULTS: the profile is a property
    # of the SubstrateToonBSDF node, not of the material, so an unbound profile
    # leaves the graph structurally perfect and artistically inert. That is
    # exactly the state this repo shipped in until 2026-10-02 - 19 TP_* assets,
    # zero bound.
    if name == "M_Master_Toon_Universal":
        profile = None
        try:
            for n in unreal.MaterialEditingLibrary.get_material_expressions(mat) or []:
                if type(n).__name__ == "MaterialExpressionSubstrateToonBSDF":
                    profile = n.get_editor_property("toon_profile")
                    break
        except Exception as exc:
            result["toon_profile_error"] = str(exc)[:120]
        result["toon_profile"] = profile.get_name() if profile else None
        if profile is None:
            result["error"] = (result.get("error", "")
                               + " | NO Toon Profile bound to the Substrate "
                                 "Toon BSDF - renders on engine defaults")

    # a zero-count graph is empty, not clean
    if len(expected_calls) > 0 and len(calls) == 0:
        result["error"] = "ZERO function calls - graph is empty, not verified"
    elif missing:
        result["error"] = f"missing calls: {missing}"
    elif nexpr < min_expressions:
        result["error"] = f"only {nexpr} expressions (expected >= {min_expressions})"
    elif result.get("error"):
        pass  # keep the earlier profile error

    result["ok"] = not result.get("error")
    log(f"VERIFY {name}: ok={result['ok']} calls={len(calls)} exprs={nexpr} "
        f"profile={result.get('toon_profile')} {result.get('error', '')}")
    return result


def save_all():
    try:
        unreal.EditorLoadingAndSavingUtils.save_dirty_packages(True, True)
        log("saved dirty packages")
    except Exception as exc:
        log(f"save_all warning: {exc}")


def write_report(report):
    REPORT.write_text(json.dumps(report, indent=2), encoding="utf-8")
    log(f"report -> {REPORT}")

def function_inputs_for(fn, node):
    """Wired upstream nodes of `node` inside a MaterialFunction.

    UE 5.8 has no get_material_expression_input(expr, pin). For FUNCTIONS the
    working call is get_inputs_for_material_function_expression(fn, node) - the
    Material-only variant takes `material` and raises a conversion error here.
    Verified by probe 2026-09-30.
    """
    lib = unreal.MaterialEditingLibrary
    try:
        return [x for x in lib.get_inputs_for_material_function_expression(fn, node)
                if x is not None]
    except Exception:
        return []


def material_inputs_for(mat, node):
    try:
        return [x for x in unreal.MaterialEditingLibrary
                .get_inputs_for_material_expression(mat, node) if x is not None]
    except Exception:
        return []


def graph_reachability(owner, nodes, is_function):
    """Backward BFS from every FunctionOutput / material property output.

    Answering "does every node contribute to a rendered output?" is the only
    meaningful dead-code test. A forward BFS from inputs is wrong: parameters
    and constants are legitimate graph SOURCES and would be miscounted as
    orphans (they have no upstream).

    Returns (live, dead, outputs_wired, unused_inputs).
    """
    nodes = list(nodes)
    get_ins = function_inputs_for if is_function else material_inputs_for

    # reverse edges: upstream -> downstream
    consumers = {}
    for n in nodes:
        for u in get_ins(owner, n):
            consumers.setdefault(id(u), []).append(id(n))

    outputs = [n for n in nodes
               if type(n).__name__ == "MaterialExpressionFunctionOutput"]
    outputs_wired = {type(n).__name__: bool(get_ins(owner, n)) for n in outputs}

    by_id = {id(n): n for n in nodes}

    # seed the walk at the sinks (nothing consumes them) and walk upstream
    live = set()
    stack = [id(n) for n in nodes if id(n) not in consumers]
    live.update(stack)
    while stack:
        cur = stack.pop()
        node = by_id.get(cur)
        if node is None:
            continue
        for u in get_ins(owner, node):
            if id(u) not in live:
                live.add(id(u)); stack.append(id(u))

    dead = len(nodes) - len(live)

    # inputs that reach nothing
    unused_inputs = []
    for n in nodes:
        if type(n).__name__ == "MaterialExpressionFunctionInput":
            if id(n) not in live:
                unused_inputs.append(str(n.get_editor_property("input_name")))

    return len(live), dead, outputs_wired, unused_inputs


def verify_function_graph(name, max_dead=0, require_outputs=True):
    """Full structural check for a generated MaterialFunction.

    Guards the failure that counting expressions cannot: a function whose nodes
    exist but whose chain never reaches the outputs renders nothing.
    """
    path = asset_path(FUNCTION_DIR, name)
    fn = unreal.load_asset(path)
    result = {"path": path, "loads": fn is not None, "ok": False}
    if fn is None:
        log(f"VERIFY FAIL {name}: does not load")
        return result

    exprs = list(unreal.MaterialEditingLibrary.get_material_function_expressions(fn) or [])
    result["expression_count"] = len(exprs)

    live, dead, outs, unused = graph_reachability(fn, exprs, is_function=True)
    result["live_nodes"] = live
    result["dead_nodes"] = dead
    result["outputs_wired"] = outs
    result["unused_inputs"] = unused

    if len(exprs) == 0:
        result["error"] = "ZERO expressions"
    elif dead > max_dead:
        result["error"] = f"{dead} nodes contribute to no output"
    elif require_outputs and outs and not all(outs.values()):
        deadouts = [k for k, v in outs.items() if not v]
        result["error"] = f"outputs have no source: {deadouts}"
    result["ok"] = not result.get("error")
    log(f"VERIFY {name}: ok={result['ok']} exprs={len(exprs)} live={live} "
        f"dead={dead} unused_inputs={unused} {result.get('error','')}")
    return result
