# Export the staged BRUTALIST review set to FBX for the Unreal import step.
#
# WHY THIS EXISTS
# ---------------
# `stage_brutalist_review.py` stages the geometry into a .blend and renders
# contact sheets, but it does NOT export exportable geometry. `Docs/ASSETLIST.md`
# records the gap: the set is "staged headless into Saved/" and "not yet in
# Content/: that needs an FBX export and an import in the editor, which is the
# remaining desktop step." This is that export.
#
# It opens the ALREADY-STAGED .blend rather than re-running the stager, so the
# geometry is identical to the reviewed contact sheets and no EEVEE render is
# paid for again.
#
# Usage (from the repo root):
#     "C:/Program Files/Blender Foundation/Blender 5.2/blender.exe" \
#         --background --factory-startup \
#         --python Blender/export_brutalist_fbx.py
#
#     -- --stamp 2026-09-30     pick a different staged .blend
#     -- --combined             additionally write one merged kit FBX
#
# Outputs:
#     Saved/Export/brutalist/<Collection>/<Object>.fbx   one per staged object
#     Saved/Export/brutalist/BRUTALIST_KIT.fbx           only with --combined
#     Saved/Audit/brutalist_fbx_manifest.json            per-object evaluated
#                                                        vert count + bbox
#
# COMPLETENESS: what gets exported is whatever the staged .blend's root
# collection carries (minus the palette swatch board), cross-checked both
# directions against the stager's manifest when that manifest names this blend.
# There is no hand-maintained collection list or object count in this script.
#
# SCALE + AXIS, measured not assumed
# --------------------------------
# `apply_unit_scale=True` ALONE carries the metres->centimetres x100. An earlier
# revision also passed `global_scale=100.0`, which compounded: a bounds probe of
# the imported meshes read SM_CITY_TightEstate at 900211 uu against an expected
# 9002 (x100 too big). `global_scale` therefore stays at 1.0; do not "restore" it.
#
# The probe also established the axis mapping from real data rather than theory:
# KMZ_TightEstate sits at Blender y=+320 m and imported with its bounds centre at
# y=-32000 uu, so Unreal Y = -(Blender Y) x 100. X and Z are unflipped. The layout
# stager keys on exactly that.
#
# GEOMETRY IS CENTRED. The exporter otherwise bakes each object's scene position
# into its vertex data, so every mesh arrives with its pivot at the world origin
# and its geometry far away -- unusable as a reusable asset. Each object is
# temporarily moved to the origin for export and restored afterwards, which leaves
# the mesh centred on its own pivot (base at Z=0) and makes placement explicit.
# The reviewed positions travel in the manifest instead.
#
# Modifiers are applied on export (use_mesh_modifiers) because the geometry is
# generated by the node tree -- an unapplied export would ship empty meshes.
import json
import os
import sys

import bpy

SCRIPT = os.path.abspath(__file__)
REPO = os.path.dirname(os.path.dirname(SCRIPT))
AUDIT = os.path.join(REPO, "Saved", "Audit")
EXPORT_SCALE = 1.0   # NOT 100 -- apply_unit_scale already does metres -> cm.

argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []


def _arg_value(flag, default):
    if flag in argv:
        i = argv.index(flag)
        if i + 1 < len(argv):
            return argv[i + 1]
    return default


STAMP = _arg_value("--stamp", "2026-09-30")
COMBINED = "--combined" in argv

BLEND = os.path.join(REPO, "Saved", "Blend", "BRUTALIST_CITY_REVIEW_%s.blend" % STAMP)
OUT_DIR = os.path.join(REPO, "Saved", "Export", "brutalist")
MANIFEST_PATH = os.path.join(AUDIT, "brutalist_fbx_manifest.json")

# What ships is what the stager's LAYOUT laid out - the collections that exist
# in the staged .blend. Listing them here BY HAND was the second copy of that
# list: adding a row to the stager (e.g. 07_OFFICE_PROPS on 2026-10-04) left the
# new objects un-exported until this list was edited in the same change. The
# .blend's root collection IS the list now; the only exclusion is the palette
# swatch board, which is a review aid, not an asset.
PALETTE_COLLECTION = "05_MATERIAL_PALETTE"
STAGE_MANIFEST = os.path.join(AUDIT, "brutalist_stage_manifest.json")


def log(m):
    print("[BrutalistExport] %s" % m, flush=True)


def open_staged_blend():
    if not os.path.exists(BLEND):
        raise SystemExit("staged .blend not found: %s" % BLEND)
    bpy.ops.wm.open_mainfile(filepath=BLEND)
    log("opened %s" % BLEND)


def layout_collections(root):
    """Export-target collections: the staged root's children minus the
    palette swatch board, in staged order.
    """
    return [c.name for c in root.children if c.name != PALETTE_COLLECTION]


def stage_manifest_objects():
    """Object names the stager staged for THIS exact blend, or None.

    The stager writes Saved/Audit/brutalist_stage_manifest.json last, and it is
    overwritten on every run, so it is only a valid cross-check when its
    `blend` field points at the blend this exporter just opened.
    """
    if not os.path.exists(STAGE_MANIFEST):
        return None
    try:
        with open(STAGE_MANIFEST, "r", encoding="utf-8") as fh:
            m = json.load(fh)
    except Exception:
        return None
    if m.get("blend") != BLEND:
        return None
    names = [e["object"] for coll in m.get("collections", {}).values()
             for e in coll]
    return names or None


def evaluated_vert_count(obj):
    """Vert count AFTER the geometry-nodes modifier -- the number that ships."""
    dg = bpy.context.evaluated_depsgraph_get()
    ev = obj.evaluated_get(dg)
    try:
        return len(ev.to_mesh().vertices)
    finally:
        ev.to_mesh_clear()


def _export_fbx(filepath):
    bpy.ops.export_scene.fbx(
        filepath=filepath,
        use_selection=True,
        object_types={'MESH'},
        apply_unit_scale=True,
        global_scale=EXPORT_SCALE,        # 1.0 -- see the headnote; 100 double-scales
        apply_scale_options='FBX_SCALE_ALL',
        axis_forward='-Y',
        axis_up='Z',
        use_mesh_modifiers=True,   # apply the node tree; else the mesh ships empty
        mesh_smooth_type='FACE',
        use_tspace=True,
        embed_textures=False,
        path_mode='AUTO',
        bake_space_transform=False,
    )


def export_object(obj, filepath):
    """Export one object with its geometry centred on its own pivot.

    The object is moved to the origin for the duration of the export so the
    written vertices are object-local; its reviewed scene position is restored
    afterwards and travels in the manifest instead.
    """
    bpy.ops.object.select_all(action='DESELECT')
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj

    saved_loc = obj.location.copy()
    obj.location = (0.0, 0.0, 0.0)
    bpy.context.view_layer.update()
    try:
        _export_fbx(filepath)
    finally:
        obj.location = saved_loc
        bpy.context.view_layer.update()


def export_combined(objs, filepath):
    # The combined kit is a whole-scene export: here the objects KEEP their
    # reviewed positions, because the point of the kit FBX is the arrangement.
    bpy.ops.object.select_all(action='DESELECT')
    for o in objs:
        o.select_set(True)
    bpy.context.view_layer.objects.active = objs[0]
    _export_fbx(filepath)


def main():
    open_staged_blend()

    root = bpy.data.collections.get("BRUTALIST_CITY_REVIEW_%s" % STAMP)
    if root is None:
        raise SystemExit("staged root collection not found: "
                         "BRUTALIST_CITY_REVIEW_%s" % STAMP)
    target_collections = layout_collections(root)
    if not target_collections:
        raise SystemExit("root collection carries no exportable collections")

    staged = stage_manifest_objects()
    if staged is not None:
        log("cross-checking against the stager manifest (%d objects)"
            % len(staged))

    manifest = {
        "stamp": STAMP,
        "blend": BLEND,
        "export_dir": OUT_DIR,
        "scale_note": "Blender metres x100 -> Unreal centimetres",
        "collections": {},
        "objects": [],
        "errors": [],
    }

    all_objs = []
    total_verts = 0

    for coll_name in target_collections:
        coll = bpy.data.collections.get(coll_name)
        if coll is None:
            manifest["errors"].append("collection missing: %s" % coll_name)
            log("MISSING collection %s" % coll_name)
            continue

        objs = [o for o in coll.objects if o.type == 'MESH']
        manifest["collections"][coll_name] = []

        for obj in sorted(objs, key=lambda o: o.name):
            out_folder = os.path.join(OUT_DIR, coll_name)
            os.makedirs(out_folder, exist_ok=True)
            fbx = os.path.join(out_folder, "%s.fbx" % obj.name)

            verts = evaluated_vert_count(obj)
            mats = [m.name for m in obj.data.materials if m]
            dims = [round(d, 3) for d in obj.dimensions]

            try:
                export_object(obj, fbx)
                size = os.path.getsize(fbx)
                ok = size > 0
            except Exception as e:                        # noqa: BLE001
                ok = False
                size = 0
                manifest["errors"].append("%s: export failed: %s" % (obj.name, e))
                log("FAILED %s: %s" % (obj.name, e))

            manifest["objects"].append({
                "object": obj.name,
                "collection": coll_name,
                "fbx": os.path.relpath(fbx, REPO).replace("\\", "/"),
                "evaluated_verts": verts,
                "dimensions_m": dims,
                "materials_blender": mats,
                "bytes": size,
                "ok": ok,
            })
            manifest["collections"][coll_name].append(obj.name)
            all_objs.append(obj)
            total_verts += verts
            log("%-24s %6d verts  %8d B  %s" % (obj.name, verts, size, coll_name))

    if COMBINED and all_objs:
        kit = os.path.join(OUT_DIR, "BRUTALIST_KIT.fbx")
        export_combined(all_objs, kit)
        manifest["combined_fbx"] = os.path.relpath(kit, REPO).replace("\\", "/")
        manifest["combined_bytes"] = os.path.getsize(kit)
        log("combined kit -> %s (%d B)" % (kit, manifest["combined_bytes"]))

    manifest["object_count"] = len(manifest["objects"])
    manifest["total_evaluated_verts"] = total_verts

    # Completeness: the old `== 25` asserted against a HAND-COUNTED number, so
    # the 2026-10-04 office-props addition (28 objects) would have failed this
    # gate even though the export was complete. The stager's manifest is the
    # count's source of truth; cross-check both directions when it is for this
    # blend, and fall back to "something shipped and nothing failed" otherwise.
    completeness_ok = bool(manifest["objects"])
    if staged is not None:
        exported = {o["object"] for o in manifest["objects"]}
        missing = [n for n in staged if n not in exported]
        extra = sorted(exported - set(staged))
        if missing:
            manifest["errors"].append("staged but not exported: %s"
                                      % ", ".join(missing))
            log("MISSING from export: %s" % ", ".join(missing))
        if extra:
            manifest["errors"].append("exported but not staged: %s"
                                      % ", ".join(extra))
            log("EXTRA in export: %s" % ", ".join(extra))
        completeness_ok = not missing and not extra
        manifest["stage_manifest_objects"] = len(staged)

    manifest["ok"] = (not manifest["errors"]
                      and completeness_ok
                      and all(o["ok"] for o in manifest["objects"]))

    os.makedirs(AUDIT, exist_ok=True)
    with open(MANIFEST_PATH, "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=1)

    log("objects=%d total_verts=%d errors=%d ok=%s"
        % (manifest["object_count"], total_verts,
           len(manifest["errors"]), manifest["ok"]))
    log("manifest -> %s" % MANIFEST_PATH)

    # The manifest is the assertion; the exit code is a convenience for CI.
    sys.exit(0 if manifest["ok"] else 1)


main()