"""Generate the capstone asset list from evidence, not from memory.

    python Tools/make_assetlist.py

Writes:
    Docs/ASSETLIST.md        human-readable, for the submission / review
    Docs/ASSETLIST_v0.csv    machine-readable, for the tracker

WHY GENERATED: this is the W4 `assetlist-v0` deliverable, and a hand-typed asset
list drifts from the project the first time somebody renames something. Everything
below is derived from real files plus the staging manifest, so re-running is always
correct and a diff means the project actually changed.

Sources of truth:
    Content/Materials/**                        the generated material assets
    Content/Maps/**                             the levels
    Content/Environment/Brutalist/**            the imported environment meshes
    Content/Sequences/**                        the shot-deck level sequences
    Saved/Audit/brutalist_stage_manifest.json   the staged brutalist objects
    Saved/Audit/brutalist_import_report.json    what the editor actually imported
    Saved/Audit/shot_deck_report.json           what the shot-deck builder built
    Saved/Audit/melodia_intake_triage_*.json    the 132-file Melodia intake drop
    Python/build_*.py                           which builder generates which asset

STATUS IS DERIVED, NOT ASSUMED. An earlier revision hard-coded the brutalist
set as "staged - not yet in Content/" and listed "Level Sequences + cameras" as
not started; once the import and the shot deck landed, it kept printing both
claims as fact. A generated report that lies is worse than no report, so the
status now comes from the import/shot-deck reports on disk.
"""
from __future__ import annotations

import csv
import json
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MANIFEST = REPO / "Saved" / "Audit" / "brutalist_stage_manifest.json"
IMPORT_REPORT = REPO / "Saved" / "Audit" / "brutalist_import_report.json"
SHOT_REPORT = REPO / "Saved" / "Audit" / "shot_deck_report.json"
LAYOUT_REPORT = REPO / "Saved" / "Audit" / "brutalist_layout_report.json"
OUT_MD = REPO / "Docs" / "ASSETLIST.md"
OUT_CSV = REPO / "Docs" / "ASSETLIST_v0.csv"
BRUTALIST_SRC = "Blender/export_brutalist_fbx.py"
SHOT_DECK_SRC = "Python/build_shot_deck.py"

# An asset with no entry here is either hand-authored (a defect, see
# Docs/CONTENT_CONVENTIONS.md) or new. Both belong in the report, not hidden.
# 2026-10-05: the staging build added ten masters and four lookdev maps that
# were previously reported as UNKNOWN despite having a builder - the map only
# ever knew the original five masters.
GENERATORS = {
    "M_Master_Toon_Universal": "Python/build_master_toon.py",
    "M_Master_Toon_Character": "Python/build_master_toon_character.py",
    "M_Master_Toon_Foliage": "Python/build_master_toon_foliage.py",
    "M_Master_Toon_Water": "Python/build_master_toon_water.py",
    "M_Master_Toon_Landscape": "Python/build_master_toon_landscape.py",
    "M_Master_Toon_Face": "Python/build_master_toon_face.py",
    "M_Master_Toon_Hair": "Python/build_master_toon_hair.py",
    "M_Master_Toon_Glass": "Python/build_master_toon_glass.py",
    "M_Master_Toon_Sky": "Python/build_m_toon_sky.py",
    "M_Master_Toon_EmissiveFX": "Python/build_m_toon_emissivefx.py",
    "M_Master_Toon_Particles": "Python/build_m_toon_particles.py",
    "M_Master_Toon_PostComposite": "Python/build_m_toon_postcomposite.py",
    "M_Toon_Unlit_Character": "Python/build_m_toon_unlit.py",
    "M_Outline_InvertedHull": "Python/build_m_outline.py",
    "MF_ColorRamp3": "Python/build_mf_colorramp3.py",
    "MF_RampLUT": "Python/build_mf_ramplut.py",
    "MF_ProceduralPatterns": "Python/build_mf_patterns.py",
    "MF_RimOffset": "Python/build_mf_rimoffset.py",
}
# The 132-file Melodia intake drop is not generated by this repo and must not
# be reported as UNKNOWN: the triage report names every target path, so the
# list can say exactly what it is (and the triage carries the per-file
# dangling-ref detail). Newest dated triage wins if more than one exists.
def intake_map() -> dict:
    cands = sorted(REPO.glob("Saved/Audit/melodia_intake_triage_*.json"))
    rep = load_json(cands[-1]) if cands else None
    if not rep:
        return {}
    name = cands[-1].name
    return {a.get("target"): name
            for a in rep.get("assets", []) if a.get("target")}

FOLDER_KIND = {
    "Masters": "master material",
    "Functions": "material function",
    "ToonProfiles": "toon profile",
    "Instances": "material instance",
    # Added 2026-10-02 with Content/Materials/Textures. Without this entry the
    # whole generated texture library (dither/hatch/ramp LUTs) was invisible in
    # ASSETLIST.md while still shipping in Content/ - the list silently
    # under-reports exactly the assets that are regenerated from Python.
    "Textures": "texture",
}
# Levels are built by more than one script now, so the origin cannot be hardcoded.
# A level with no entry here reports UNKNOWN rather than a wrong builder.
MAP_GENERATORS = {
    "L_Toon_Lookdev": "Python/build_test_level.py",
    "L_Brutalist_Layout": "Python/stage_brutalist_layout.py",
    "L_Foliage_Lookdev": "Python/build_foliage_lookdev.py",
    "L_Gouache_Lookdev": "Python/build_gouache_lookdev.py",
    "L_Water_Lookdev": "Python/build_water_lookdev.py",
    "L_Toon_Shot_Env": "Python/compose_shot_env_level.py",
}
FIELDS = ["id", "name", "category", "source", "origin", "path",
          "verts", "materials", "owner", "status"]


def generator_for(asset: str, folder: str, rel: str = "",
                  intake: dict | None = None) -> str:
    if intake and rel in intake:
        return "Melodia intake drop (Saved/Audit/%s)" % intake[rel]
    if asset in GENERATORS:
        return GENERATORS[asset]
    if folder == "ToonProfiles":
        return "Python/build_toon_profiles.py"
    if folder == "Instances":
        return "Python/build_instances.py"
    if folder == "Textures":
        return "Python/build_textures.py"
    return "UNKNOWN - not generated by any builder"


def load_json(path: Path):
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:                                          # noqa: BLE001
        return None


def count_uassets(folder: Path) -> int:
    if not folder.is_dir():
        return 0
    return len(list(folder.rglob("*.uasset")))


def imported_shots():
    """Shot rows from the shot-deck report. Empty when the deck was not built."""
    rep = load_json(SHOT_REPORT)
    if not rep or not rep.get("shots"):
        return []
    rows = []
    for s in rep["shots"]:
        seq_name = s["sequence"].rsplit("/", 1)[-1]
        rows.append({
            "id": seq_name, "name": s.get("name", ""),
            "category": s.get("name", "shot"),
            "source": "code-generated",
            "origin": SHOT_DECK_SRC,
            "path": "Content/Sequences/%s.uasset" % seq_name,
            "verts": "", "materials": "cam=%s %smm" % (s.get("camera"),
                                                       s.get("focal_length_mm")),
            "owner": "TBD",
            "status": "in repo (%d-%d @%s fps)" % (s.get("playback_start"),
                                                   s.get("playback_end"),
                                                   rep.get("fps", 24)),
        })
    return rows


def collect():
    rows = []
    intake = intake_map()
    mat_root = REPO / "Content" / "Materials"
    for sub in ("Masters", "Functions", "ToonProfiles", "Instances", "Textures"):
        d = mat_root / sub
        if not d.is_dir():
            continue
        for f in sorted(d.glob("*.uasset")):
            rel = str(f.relative_to(REPO)).replace("\\", "/")
            rows.append({
                "id": f.stem, "name": f.stem,
                "category": FOLDER_KIND.get(sub, sub),
                "source": ("imported (Melodia)" if rel in intake
                           else "code-generated"),
                "origin": generator_for(f.stem, sub, rel, intake),
                "path": rel,
                "verts": "", "materials": "", "owner": "TBD",
                "status": "in repo",
            })

    maps = REPO / "Content" / "Maps"
    for f in sorted(maps.glob("*.umap")):
        rows.append({
            "id": f.stem, "name": f.stem, "category": "level",
            "source": "code-generated",
            "origin": MAP_GENERATORS.get(f.stem, "UNKNOWN - no builder mapped"),
            "path": str(f.relative_to(REPO)).replace("\\", "/"),
            "verts": "", "materials": "", "owner": "TBD", "status": "in repo",
        })
    hl = maps / "L_Toon_Lookdev_HLOD0_Instancing.uasset"
    if hl.exists():
        rows.append({
            "id": hl.stem, "name": "Lookdev HLOD0 instancing",
            "category": "generated data", "source": "code-generated",
            "origin": "editor HLOD build",
            "path": str(hl.relative_to(REPO)).replace("\\", "/"),
            "verts": "", "materials": "", "owner": "TBD",
            "status": "in repo (regenerable)",
        })

    brutalist, sheets = [], []
    if MANIFEST.exists():
        m = json.loads(MANIFEST.read_text(encoding="utf-8"))
        for coll, objs in (m.get("collections") or {}).items():
            for o in objs:
                brutalist.append({
                    "id": o.get("object", "?"), "name": o.get("object", "?"),
                    "category": "brutalist object (staged)",
                    "source": "code-generated",
                    "origin": "Blender/%s / %s"
                              % (o.get("builder", "?"), o.get("preset", "?")),
                    "path": coll,
                    "verts": o.get("verts", ""),
                    "materials": ",".join(o.get("materials") or []),
                    "owner": "TBD", "status": "staged - not yet in Content/",
                })
        sheets = sorted((m.get("sheets") or {}).keys())
    return rows, brutalist, sheets


def main() -> int:
    rows, brutalist, sheets = collect()
    shots = imported_shots()
    today = date.today().isoformat()

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=FIELDS)
        w.writeheader()
        for r in rows + brutalist + shots:
            w.writerow(r)

    total_verts = 0
    for b in brutalist:
        try:
            total_verts += int(b["verts"])
        except (TypeError, ValueError):
            pass

    md = []
    md.append("# Asset list (v0)\n")
    md.append("Generated %s by `Tools/make_assetlist.py` - do not hand-edit, "
              "re-run it.\n" % today)
    md.append("This is the W4 `assetlist-v0` deliverable. `Owner` is deliberately "
              "blank: assign it in the group, per asset, before the first shared "
              "edit (see `Docs/GROUP_WORKFLOW.md`).\n")
    md.append("Machine-readable twin: `Docs/ASSETLIST_v0.csv`\n")

    md.append("\n## Shipped toon spine (in repo)\n")
    md.append("| Asset | Kind | Generated by | Path |\n|---|---|---|---|")
    for r in rows:
        md.append("| `%s` | %s | `%s` | `%s` |"
                  % (r["id"], r["category"], r["origin"], r["path"]))
    unknown = [r["id"] for r in rows if r["origin"].startswith("UNKNOWN")]
    md.append("\n**%d assets.**%s\n"
              % (len(rows),
                 "" if not unknown
                 else " Assets with no generator to decide on: %s."
                      % ", ".join("`%s`" % u for u in unknown)))

    md.append("\n## Brutalist building set (environment kit)\n")
    if brutalist:
        import_counts = {}
        imp = load_json(IMPORT_REPORT)
        if imp:
            for rec in imp.get("imported", []):
                import_counts[rec["collection"]] = import_counts.get(
                    rec["collection"], 0) + 1
        imported_total = sum(import_counts.values())
        n_meshes = count_uassets(REPO / "Content" / "Environment" / "Brutalist")

        md.append("| Object | Collection | Builder / preset | Verts | Materials | "
                  "Status |\n|---|---|---|---|---|---|")
        for r in brutalist:
            coll = r["path"]
            status = ("in Content/ (SM_%s)" % r["id"]
                      if import_counts.get(coll, 0) else "staged only - not imported")
            md.append("| `%s` | %s | %s | %s | %s | %s |"
                      % (r["id"], coll, r["origin"], r["verts"],
                         r["materials"], status))
        md.append("\n**%d objects, %s verts total**, staged under 6 collections. "
                  "Contact sheets: %s.\n"
                  % (len(brutalist), format(total_verts, ","),
                     ", ".join("`%s`" % s for s in sheets) or "none recorded"))
        if imported_total:
            md.append("Exported by `%s` and imported into `Content/Environment/"
                      "Brutalist/` by `Python/import_brutalist.py`: **%d of %d "
                      "objects imported**, %d `SM_*` mesh assets on disk** "
                      "(verified: `%s`). Assignment per object is per-surface "
                      "(`MI_Toon_Environment` on every slot as the starting "
                      "point); the id is the Blender object name and the asset "
                      "adds the `SM_` prefix. See `Docs/BRUTALIST_SET.md`.\n"
                      % (BRUTALIST_SRC, imported_total, len(brutalist), n_meshes,
                         "Saved/Audit/brutalist_import_report.json"))
            lay = load_json(LAYOUT_REPORT)
            if lay and lay.get("verify", {}).get("ok"):
                md.append("Staged into `Content/Maps/L_Brutalist_Layout.umap` by "
                          "`Python/stage_brutalist_layout.py` at the reviewed "
                          "positions from the stage manifest: **%d actors, no "
                          "overlaps**. That arrangement is a REVIEW GRID (six "
                          "rows of variants for contact-sheet comparison), not a "
                          "shot scene -- composing the kit into a shot is a "
                          "separate creative step. Verified: `%s`.\n"
                          % (lay.get("placed_count"),
                             "Saved/Audit/brutalist_layout_report.json"))
        else:
            md.append("Blender exports the FBX and `Python/import_brutalist.py` "
                      "imports them; **no import report found**, so the set is "
                      "still staged-only. Run the import before shipping a "
                      "clone. See `Docs/BRUTALIST_SET.md`.\n")
    else:
        md.append("No staging manifest found - run the Blender stager first: "
                  "`Blender/stage_brutalist_review.py`.\n")

    md.append("\n## Shot deck (level sequences + cameras)\n")
    if shots:
        md.append("| Sequence | Shot | Camera | Frames | Source |\n"
                  "|---|---|---|---|---|")
        for s in shots:
            md.append("| `%s` | %s | %s | %s | `%s` |"
                      % (s["id"], s["category"], s["materials"],
                         s["status"].replace("in repo (", "").rstrip(")"),
                         s["origin"]))
        md.append("\n**%d `LS_*` sequences** built from "
                  "`specs/humber_toon_spine/humber_toon_spine_manifest.v1.json` "
                  "by `%s`; cameras are `CineCameraActor`s in `L_Toon_Lookdev`. "
                  "Frames are the manifest's cut list, converted to Sequencer's "
                  "0-based range. Verified: "
                  "`Saved/Audit/shot_deck_report.json`.\n"
                  % (len(shots), SHOT_DECK_SRC))
    else:
        md.append("No shot-deck report found - run `%s` with the editor open.\n"
                  % SHOT_DECK_SRC)

    md.append("\n## Not yet started\n")
    md.append("| Area | Needed for | Owner |\n|---|---|---|")
    md.append("| Characters (mesh, rig, materials) | every shot with a character | TBD |")
    md.append("| Props / set dressing | environment shots | TBD |")
    md.append("| MRQ render presets | final render | TBD |")
    md.append("| Audio / score | final cut | TBD |")
    md.append("| Shot camera moves / blocking | every shot | TBD |")
    if not shots:
        md.append("| Level Sequences + cameras | all shots | TBD |")

    OUT_MD.write_text("\n".join(md) + "\n", encoding="utf-8")
    print("assetlist: %d spine assets + %d brutalist objects (%s verts) "
          "+ %d shot sequences"
          % (len(rows), len(brutalist), format(total_verts, ","), len(shots)))
    print("  -> %s" % OUT_MD)
    print("  -> %s" % OUT_CSV)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

