"""Generate the capstone asset list from evidence, not from memory.

    python Tools/make_assetlist.py

Writes:
    Docs/ASSETLIST.md        human-readable, for the submission / review
    Docs/ASSETLIST_v0.csv    machine-readable, for the tracker

WHY GENERATED: this is the W4 `assetlist-v0` deliverable, and a hand-typed asset
list drifts from the project the first time somebody renames something. Everything
below is derived from real files plus the staging manifest, so re-running is always
correct and a diff means the project actually changed.

Sources of truth:
    Content/Materials/**                        the generated material assets
    Content/Maps/**                             the levels
    Saved/Audit/brutalist_stage_manifest.json   the staged brutalist objects
    Python/build_*.py                           which builder generates which asset
"""
from __future__ import annotations

import csv
import json
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MANIFEST = REPO / "Saved" / "Audit" / "brutalist_stage_manifest.json"
OUT_MD = REPO / "Docs" / "ASSETLIST.md"
OUT_CSV = REPO / "Docs" / "ASSETLIST_v0.csv"

# An asset with no entry here is either hand-authored (a defect, see
# Docs/CONTENT_CONVENTIONS.md) or new. Both belong in the report, not hidden.
GENERATORS = {
    "M_Master_Toon_Universal": "Python/build_master_toon.py",
    "M_Outline_InvertedHull": "Python/build_m_outline.py",
    "MF_ColorRamp3": "Python/build_mf_colorramp3.py",
    "MF_RampLUT": "Python/build_mf_ramplut.py",
    "MF_ProceduralPatterns": "Python/build_mf_patterns.py",
}
FOLDER_KIND = {
    "Masters": "master material",
    "Functions": "material function",
    "ToonProfiles": "toon profile",
    "Instances": "material instance",
}
FIELDS = ["id", "name", "category", "source", "origin", "path",
          "verts", "materials", "owner", "status"]


def generator_for(asset: str, folder: str) -> str:
    if asset in GENERATORS:
        return GENERATORS[asset]
    if folder == "ToonProfiles":
        return "Python/build_toon_profiles.py"
    if folder == "Instances":
        return "Python/build_instances.py"
    return "UNKNOWN - not generated by any builder"


def collect():
    rows = []
    mat_root = REPO / "Content" / "Materials"
    for sub in ("Masters", "Functions", "ToonProfiles", "Instances"):
        d = mat_root / sub
        if not d.is_dir():
            continue
        for f in sorted(d.glob("*.uasset")):
            rows.append({
                "id": f.stem, "name": f.stem,
                "category": FOLDER_KIND.get(sub, sub),
                "source": "code-generated",
                "origin": generator_for(f.stem, sub),
                "path": str(f.relative_to(REPO)).replace("\\", "/"),
                "verts": "", "materials": "", "owner": "TBD",
                "status": "in repo",
            })

    maps = REPO / "Content" / "Maps"
    for f in sorted(maps.glob("*.umap")):
        rows.append({
            "id": f.stem, "name": f.stem, "category": "level",
            "source": "code-generated",
            "origin": "Python/build_test_level.py",
            "path": str(f.relative_to(REPO)).replace("\\", "/"),
            "verts": "", "materials": "", "owner": "TBD", "status": "in repo",
        })
    hl = maps / "L_Toon_Lookdev_HLOD0_Instancing.uasset"
    if hl.exists():
        rows.append({
            "id": hl.stem, "name": "Lookdev HLOD0 instancing",
            "category": "generated data", "source": "code-generated",
            "origin": "editor HLOD build",
            "path": str(hl.relative_to(REPO)).replace("\\", "/"),
            "verts": "", "materials": "", "owner": "TBD",
            "status": "in repo (regenerable)",
        })

    brutalist, sheets = [], []
    if MANIFEST.exists():
        m = json.loads(MANIFEST.read_text(encoding="utf-8"))
        for coll, objs in (m.get("collections") or {}).items():
            for o in objs:
                brutalist.append({
                    "id": o.get("object", "?"), "name": o.get("object", "?"),
                    "category": "brutalist object (staged)",
                    "source": "code-generated",
                    "origin": "Blender/%s / %s"
                              % (o.get("builder", "?"), o.get("preset", "?")),
                    "path": coll,
                    "verts": o.get("verts", ""),
                    "materials": ",".join(o.get("materials") or []),
                    "owner": "TBD", "status": "staged - not yet in Content/",
                })
        sheets = sorted((m.get("sheets") or {}).keys())
    return rows, brutalist, sheets


def main() -> int:
    rows, brutalist, sheets = collect()
    today = date.today().isoformat()

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=FIELDS)
        w.writeheader()
        for r in rows + brutalist:
            w.writerow(r)

    total_verts = 0
    for b in brutalist:
        try:
            total_verts += int(b["verts"])
        except (TypeError, ValueError):
            pass

    md = []
    md.append("# Asset list (v0)\n")
    md.append("Generated %s by `Tools/make_assetlist.py` - do not hand-edit, "
              "re-run it.\n" % today)
    md.append("This is the W4 `assetlist-v0` deliverable. `Owner` is deliberately "
              "blank: assign it in the group, per asset, before the first shared "
              "edit (see `Docs/GROUP_WORKFLOW.md`).\n")
    md.append("Machine-readable twin: `Docs/ASSETLIST_v0.csv`\n")

    md.append("\n## Shipped toon spine (in repo)\n")
    md.append("| Asset | Kind | Generated by | Path |\n|---|---|---|---|")
    for r in rows:
        md.append("| `%s` | %s | `%s` | `%s` |"
                  % (r["id"], r["category"], r["origin"], r["path"]))
    unknown = [r["id"] for r in rows if r["origin"].startswith("UNKNOWN")]
    md.append("\n**%d assets.**%s\n"
              % (len(rows),
                 "" if not unknown
                 else " Assets with no generator to decide on: %s."
                      % ", ".join("`%s`" % u for u in unknown)))

    md.append("\n## Brutalist building set (staged, desktop import pending)\n")
    if brutalist:
        md.append("| Object | Collection | Builder / preset | Verts | Materials |\n"
                  "|---|---|---|---|---|")
        for r in brutalist:
            md.append("| `%s` | %s | %s | %s | %s |"
                      % (r["id"], r["path"], r["origin"],
                         r["verts"], r["materials"]))
        md.append("\n**%d objects, %s verts total**, staged under 6 collections. "
                  "Contact sheets: %s.\n"
                  % (len(brutalist), format(total_verts, ","),
                     ", ".join("`%s`" % s for s in sheets) or "none recorded"))
        md.append("These live in `Blender/` as geometry-node builders and are "
                  "staged headless into `Saved/`. They are **not yet in "
                  "`Content/`**: that needs an FBX export and an import in the "
                  "editor, which is the remaining desktop step. See "
                  "`Docs/BRUTALIST_SET.md`.\n")
    else:
        md.append("No staging manifest found - run the Blender stager first: "
                  "`Blender/stage_brutalist_review.py`.\n")

    md.append("\n## Not yet started\n")
    md.append("| Area | Needed for | Owner |\n|---|---|---|")
    md.append("| Characters (mesh, rig, materials) | every shot with a character | TBD |")
    md.append("| Props / set dressing | environment shots | TBD |")
    md.append("| Level Sequences + cameras | all shots | TBD |")
    md.append("| MRQ render presets | final render | TBD |")
    md.append("| Audio / score | final cut | TBD |")

    OUT_MD.write_text("\n".join(md) + "\n", encoding="utf-8")
    print("assetlist: %d spine assets + %d brutalist objects (%s verts)"
          % (len(rows), len(brutalist), format(total_verts, ",")))
    print("  -> %s" % OUT_MD)
    print("  -> %s" % OUT_CSV)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

